### ISSUE TITLE
DOM issue, I think... it's wierd

### ISSUE THREAD

**Issue by rbwilde** [rbwilde/rbwilde.github.io#2]
I'm sending you two screen shots. I've been going through and trying to make the betting function and testing certain things and everything is going along just fine then I get this weird error. 

```
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
```

The first thing I think is I don't have a toLowerCase method in my code. That's weird. So I look at the line. It's saying the error is on line 7328. Well I certainly do not have 7000 lines of code. When I click on the error it takes me to some jQuery code involving hooks and shit. I double checked my links in the html. What dark magic is this and how do I get rid of it? 

![screen shot 2015-07-17 at 10 22 51 am](https://cloud.githubusercontent.com/assets/10886886/8749318/d1b561b8-2c6e-11e5-9471-97b81a93f9e2.png)
![screen shot 2015-07-17 at 10 22 59 am](https://cloud.githubusercontent.com/assets/10886886/8749322/d5340ad8-2c6e-11e5-8625-53946d02bc3d.png)

**Comment by rbwilde** [comment]
OH! It's something to do with the jQuery script tag in my html. 

```
<script src="https://code.jquery.com/jquery-2.1.4.js"></script>
```

That's what I have.... should I try a different one? Why is it giving me a problem now? It was working fine.

**Comment by andrewfritz86** [comment]
Just thinking out loud here before we meet... the issue probably isn't qith jquery, it's that jquery is being invoked at some point and there is an issue with the element it's being called on.

**Comment by andrewfritz86** [comment]
Also, can you push your code to origin master so I could look at it?

**Comment by andrewfritz86** [comment]
OK. The issue is actually on line 35. Comment out that line, and it should work. You are calling .val on a jquery object, which will return a string, and the trying to wrap that sring in jquery with another dollar sign, which won't work.
